/**
 * Spellcheck Rules
 * 
 * Enforces meaningful and correctly spelled variable/function names
 * for code clarity and maintainability.
 */

module.exports = {
    'spellcheck/spell-checker': [
        'warn',
        {
            comments: true,
            strings: false,
            identifiers: true,
            lang: 'en_US',
            skipWords: [
                // Common programming terms
                'async',
                'await',
                'bool',
                'boolean',
                'calc',
                'callback',
                'config',
                'configs',
                'const',
                'ctx',
                'dev',
                'devops',
                'enum',
                'env',
                'eslint',
                'fn',
                'func',
                'href',
                'html',
                'http',
                'https',
                'impl',
                'init',
                'instanceof',
                'json',
                'jsx',
                'keyof',
                'len',
                'middleware',
                'namespace',
                'nav',
                'nodejs',
                'noop',
                'nullable',
                'param',
                'params',
                'parseInt',
                'pathname',
                'readonly',
                'rerender',
                'req',
                'res',
                'rgba',
                'src',
                'stderr',
                'stdin',
                'stdout',
                'str',
                'stringify',
                'svg',
                'tsx',
                'typeof',
                'ui',
                'undef',
                'url',
                'urls',
                'utf',
                'util',
                'utils',
                'uuid',
                'webpack',
                'whitespace',
                'xhr',
                'xml',

                // TypeScript specific
                'tsconfig',
                'tslint',
                'dts',
                'keyof',
                'readonly',

                // React specific
                'classname',
                'classnames',
                'componentdidmount',
                'componentwillunmount',
                'createref',
                'forwardref',
                'getinitialprops',
                'getstaticprops',
                'getserversideprops',
                'onclick',
                'onchange',
                'onsubmit',
                'onkeydown',
                'onkeyup',
                'onmouseenter',
                'onmouseleave',
                'onfocus',
                'onblur',
                'unmount',
                'usestate',
                'useeffect',
                'usememo',
                'usecallback',
                'useref',
                'usecontext',
                'usereducer',
                'uselayouteffect',
                'useimperativehandle',
                'usedebugvalue',

                // Common abbreviations
                'api',
                'apis',
                'auth',
                'btn',
                'cta',
                'db',
                'dto',
                'dtos',
                'guid',
                'guids',
                'i18n',
                'id',
                'ids',
                'idx',
                'img',
                'imgs',
                'io',
                'ips',
                'js',
                'lib',
                'libs',
                'localstorage',
                'msg',
                'num',
                'obj',
                'ok',
                'os',
                'pdf',
                'pdfs',
                'prev',
                'pwa',
                'rgb',
                'sdk',
                'sql',
                'ssr',
                'ssg',
                'tmp',
                'ts',
                'txt',
                'vm',
                'vs',
                'ws',
                'wss',

                // Domain-specific (add your own)
                'auth',
                'jwt',
                'oauth',
                'oauth2',
                'saml',
                'ldap',
                'csrf',
                'xss',
                'cors',
                'cdn',
                'dns',
                'ssl',
                'tls',

                // Framework/Library names
                'axios',
                'lodash',
                'dayjs',
                'luxon',
                'zod',
                'yup',
                'formik',
                'chakra',
                'tailwind',
                'vite',
                'vitest',
                'jest',
                'mocha',
                'chai',
                'sinon',
                'playwright',
                'cypress',
                'storybook',
                'nextjs',
                'vercel',
                'netlify',
                'heroku',
                'kubernetes',
                'k8s',
                'docker',
                'redis',
                'mongodb',
                'postgres',
                'prisma',
                'sequelize',
                'typeorm',
                'graphql',
                'apollo',
                'trpc',

                // Event names (kebab-case components)
                'keydown',
                'keyup',
                'keypress',
                'mousedown',
                'mouseup',
                'mousemove',
                'mouseenter',
                'mouseleave',
                'mouseover',
                'mouseout',
                'touchstart',
                'touchend',
                'touchmove',
                'focusin',
                'focusout',
                'dragstart',
                'dragend',
                'dragover',
                'dragleave',
                'pointerdown',
                'pointerup',
                'pointermove',
            ],
            skipIfMatch: [
                // Skip hex colors
                '^#[0-9a-fA-F]{3,8}$',
                // Skip URLs
                '^https?://',
                // Skip file paths
                '^\\./',
                '^\\.\\./',
                // Skip version numbers
                '^v?\\d+\\.\\d+\\.\\d+',
                // Skip UUIDs
                '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
                // Skip base64
                '^[A-Za-z0-9+/]+=*$',
            ],
            skipWordIfMatch: [
                // Skip camelCase compound words
                '^[a-z]+[A-Z]',
            ],
            minLength: 3,
        },
    ],
};
